# Required to run
hostKey:

replicaCount: 1

image:
  repository: prasunanand/kubessh-kubessh
  tag: latest
  pullPolicy: Always

  name: prasunanand/kubessh-kubessh
service:
  type: LoadBalancer
  port: 22
  nodePort: 32222

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true

auth:
  type: github
  github:
    allowedUsers: []
